variable "project" {}
variable "source_dir" {}
variable "region" {}
variable "project_name" {}
variable "slack_webhook_url_secret_id" {}
variable "channel_name" {}
variable "openai_api_key_secret_id" {}
variable "pinecone_api_key_secret_id" {}
variable "pinecone_environment" {}
variable "index_name" {}
variable "pubsub_invoker_email" {}
variable "subscriber_runner_email" {}