variable "project" {}
variable "source_dir" {}
variable "region" {}
variable "project_name" {}
variable "slack_webhook_url" {}
variable "channel_name" {}
variable "openai_api_key" {}
variable "pinecone_api_key" {}
variable "pinecone_environment" {}
variable "index_name" {}